name: servy_mock_server
description: Mock REST API server for Servy food delivery app
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  path: ^1.9.0

